image: python:3.7.4-alpine3.10

pipelines:
  tags:
    ecr-release-*:
      - step:
          services:
            - docker
          caches:
            - pip
          script:
            - pip3 install awscli
            - IMAGE="${ECR_REPOSITORY}"
            - TAG=${BITBUCKET_BRANCH:-$BITBUCKET_TAG}
            - aws configure set AWS_SECRET_ACCESS_ID "${AWS_ACCESS_KEY_ID}"
            - aws configure set AWS_SECRET_ACCESS_KEY "${AWS_SECRET_ACCESS_KEY}"
            - eval $(aws ecr get-login --no-include-email --region ap-south-1 | sed 's|https://||')
            - docker build -t $IMAGE:$TAG .
            - docker push $IMAGE:$TAG
definitions:
  services:
    docker:
      memory: 2048